[shell]
args = ['--login']
program = "/usr/bin/zsh"

[cursor]
style = "Beam"
vi_mode_style = "Beam"

[font]
size = 12.0
normal = {family ="JetBrainsMonoNL NFM" , style="SemiBold"}
italic = {family ="JetBrainsMonoNL NFM" , style="SemiBold Italic"}
bold = {family="JetbrainsMonoNL NFM" , style="ExtraBold"}
bold_italic = {family="JetBrainsMonoNL NFM" , style="ExtraBold Italic"}

[window]
startup_mode = "Windowed"
dynamic_padding = false
opacity = 0.8
decorations = "None"
blur = true
dynamic_title = false

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 90
lines = 25

[colors.normal]
black = "#21222c"
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#f8f8f2"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"





[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true


